apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./apiserver
- ./clustersynchro-manager
- ./controller-manager
- ./crds
- ./internalstorage/postgres

patches:
- path: patches.yaml
  target:
    kind: Clusterpedia
