apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterpedia-clustersynchro-manager
  namespace: clusterpedia-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterpedia-clustersynchro-manager
  namespace: clusterpedia-system
  labels:
    app: clusterpedia-clustersynchro-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterpedia-clustersynchro-manager
  template:
    metadata:
      labels:
        app: clusterpedia-clustersynchro-manager
    spec:
      containers:
      - name: manager
        image: ghcr.io/clusterpedia-io/clusterpedia/clustersynchro-manager:v0.8.0
        command:
        - /usr/local/bin/clustersynchro-manager
        - --storage-config=/etc/clusterpedia/storage/internalstorage-config.yaml
        - --feature-gates=PruneManagedFields=true,PruneLastAppliedConfiguration=true
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: internalstorage-password
              key: password
        volumeMounts:
        - name: internalstorage-config
          mountPath: /etc/clusterpedia/storage
          readOnly: true
      serviceAccountName: clusterpedia-clustersynchro-manager
      volumes:
      - name: internalstorage-config
        configMap:
          name: clusterpedia-internalstorage
