apiVersion: v1
entries:
  clusterpedia:
  - apiVersion: v2
    appVersion: v0.5.1
    created: "2022-09-30T14:58:21.204605+08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.x.x
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.x.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: A Helm chart for Kubernetes
    digest: f15aa134fd718f0c4d3b33a2f157c873cb812ab9b1deb1bf76c151ae4082b2a8
    maintainers:
    - name: clusterpedia-io
      url: https://github.com/clusterpedia-io/clusterpedia
    name: clusterpedia
    sources:
    - https://github.com/clusterpedia-io/clusterpedia
    type: application
    urls:
    - https://github.com/clusterpedia-io/clusterpedia/releases/download/v0.5.1/clusterpedia-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: v0.5.0
    created: "2022-09-30T14:58:21.229403+08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.x.x
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.x.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: A Helm chart for Kubernetes
    digest: 0bd7ed0cba5b6f4fa041c7c003e00c9d433a5223a5e456a0f811508aa004d70c
    maintainers:
    - name: clusterpedia-io
      url: https://github.com/clusterpedia-io/clusterpedia
    name: clusterpedia
    sources:
    - https://github.com/clusterpedia-io/clusterpedia
    type: application
    urls:
    - https://github.com/clusterpedia-io/clusterpedia/releases/download/v0.5.0/clusterpedia-0.5.0.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: v0.5.0-beta.0
    created: "2022-09-30T14:58:21.218609+08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.x.x
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.x.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: A Helm chart for Kubernetes
    digest: 6f336c45b0ed66edf15b98589c0ac8a52243756255638059d9c658b78b46027e
    maintainers:
    - name: clusterpedia-io
      url: https://github.com/clusterpedia-io/clusterpedia
    name: clusterpedia
    sources:
    - https://github.com/clusterpedia-io/clusterpedia
    type: application
    urls:
    - https://github.com/clusterpedia-io/clusterpedia/releases/download/v0.5.0-beta.0/clusterpedia-0.5.0-beta.0.tgz
    version: 0.0.2
generated: "2022-09-30T14:58:21.186707+08:00"
