apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterpedia.internalstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  internalstorage-config.yaml: |-
    type: {{ include "clusterpedia.storage.type" . | quote }}
    host: {{ include "clusterpedia.storage.host" . | quote }}
    port: {{ include "clusterpedia.storage.port" . }}
    user: {{ include "clusterpedia.storage.user" . }}
    database: {{ include "clusterpedia.storage.database" . }}
    {{ if .Values.storageConfig.log.enabled }}
    log:
      stdout: {{ .Values.storageConfig.log.stdout }}
      level: {{ .Values.storageConfig.log.level | default "Warn" | quote }}
      slowThreshold: {{ .Values.storageConfig.log.slowThreshold }}
      ignoreRecordNotFoundError: {{ .Values.storageConfig.log.ignoreRecordNotFoundError }}
      logger:
        filename: {{ .Values.storageConfig.log.logger.filename }}
        maxsize: {{ .Values.storageConfig.log.logger.maxsize }}
        maxbackups: {{ .Values.storageConfig.log.logger.maxbackups }}
    {{ end }}
    connPool:
      maxIdleConns: {{ .Values.storageConfig.connPool.maxIdleConns | int }}
      maxOpenConns: {{ .Values.storageConfig.connPool.maxOpenConns | int }}
      connMaxLifetime: {{ .Values.storageConfig.connPool.connMaxLifetime }}
